name = "ThymusABM"
uuid = "ab35cdf2-b1c9-4346-b084-4932e5a6841c"
authors = ["etmulle <mulle@cshl.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
